name: Build and Release Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [win32, mac, linux]

    runs-on: ${{ matrix.platform == 'win32' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install electron-builder
      run: npm install electron-builder@latest

    - name: Build App
      run: |
        if [ "${{ matrix.platform }}" == "win32" ]; then
          npm run build:win
        elif [ "${{ matrix.platform }}" == "mac" ]; then
          electron-builder --mac
        elif [ "${{ matrix.platform }}" == "linux" ]; then
          electron-builder --linux
        fi
      env:
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

    - name: Create Release Notes
      id: create_release_notes
      run: |
        echo "## Changes" > release_notes.md
        echo "" >> release_notes.md
        awk '/^## $/{flag=0} flag; /^## \['$GITHUB_REF_NAME'$/{flag=1}' CHANGELOG.md >> release_notes.md
        echo "" >> release_notes.md
        echo "## Compare Changes" >> release_notes.md
        echo "[$GITHUB_REF_NAME...main](https://github.com/${GITHUB_REPOSITORY}/compare/$GITHUB_REF_NAME...main)" >> release_notes.md

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}-build
        path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.platform }}-build
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/*
        body_path: ./release_notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update CHANGELOG.md
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md with compare link for $GITHUB_REF_NAME"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
